---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/wordcloud (1)/wordcloud (1).svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/320467/master/file/figures/wordcloud%20(1)/wordcloud%20(1).svg"
