---
version: 2
multicolumn: false
web-width: 1500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Multiple_alignment_copy1/Multiple_alignment_copy1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/320467/master/file/figures/Multiple_alignment_copy1/Multiple_alignment_copy1.png"
    folder_url: "/users/74776/articles/320467/master/folder/figures/Multiple_alignment_copy1"
