---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/fimmu-06-00387-g002/fimmu-06-00387-g002.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/320467/master/file/figures/fimmu-06-00387-g002/fimmu-06-00387-g002.png"
